### ISSUE TITLE
[Feature] Comment block support

### ISSUE THREAD

**Issue by thezenelson** [cornell-zhang/allo#145]
**Problem**
The standard python convention for docstrings requires that it is in the form of a block comment (using """). However, in allo functions comments blocks aren't properly ignored and throw an error.

**Solution**
Support for comment blocks would allow for standard doc strings to work.

**Comment by chhzh123** [comment]
Could you provide an example? I didn't quite get the issue here.

**Comment by chhzh123** [comment]
You mean you need to use docstring in an Allo kernel? This would need to enhance the parser

**Comment by thezenelson** [comment]
![image](https://github.com/cornell-zhang/allo/assets/15502907/ad7d7fa4-5509-4854-9cdc-af68f4454a13)
This code will give an unsupported constant type. It would be great if the parser could handle conventional block comments like this. Based on their possession they're automatically treated as docstrings which is a great quality of life feature when using functions/libraries you didn't write/write recently.

**Comment by thezenelson** [comment]
This is a min test case that breaks because of the block comment.
```
def min_test():
    def top(x_in: "int8[1]") -> "int8":
        """Test text"""
        return x_in[0]

    print(allo.customize(top).build()(np.array([5], dtype=np.int8)))```
