### ISSUE TITLE
TypeError: Schedule.unfold() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by zeroherolin** [cornell-zhang/allo#174]
I followed <**5.1 Schedule Construction**> of [the paper](https://arxiv.org/abs/2404.04815), and crashed into errors.
Has the code feature been updated? Please help me with my fixing bugs.
```
import allo
from allo.ir.types import int8, int16

M, N, K = 1024, 1024, 1024


# Algorithm specification
def gemm(A: int8[M, K], B: int8[K, N]) -> int16[M, N]:
    C: int16[M, N] = 0
    for i, j in allo.grid(M, N, name="PE"):
        for k in allo.reduction(K):
            C[i, j] += A[i, k] * B[k, j]
    return C


# Schedule construction
s = allo.customize(gemm)
buf_A = s.buffer_at(s.A, "j")  # p0
buf_B = s.buffer_at(s.B, "j")  # p1
pe = s.unfold("PE", axis=[0, 1])  # p2
s.partition(s.C, dim=[0, 1])  # p3
s.partition(s.A, dim=0)  # p4
s.partition(s.B, dim=1)  # p5
s.relay(buf_A, pe, axis=1, depth=M + 1)  # p6
s.relay(buf_B, pe, axis=0, depth=N + 1)  # p7
```

> error: Cannot buffer at the inner-most loop: axis=1 inner-most axis=1
> Traceback (most recent call last):
>   File "/home/xilinx/Desktop/allo_dsl/pythonProject/app.py", line 20, in <module>
>     pe = s.unfold("PE", axis=[0, 1])  # p2
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/xilinx/allo/allo/customize.py", line 108, in wrapper
>     res = fn(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^
> TypeError: Schedule.unfold() got an unexpected keyword argument 'axis'

**Comment by zzzDavid** [comment]
Hi, thanks for trying out our project! There's a slight semantic difference, the axis is not a keyword argument here. Also we use `s.to` as the equivalence of the `s.relay`, please check this test case here:
https://github.com/cornell-zhang/allo/blob/1e76376835a395f8660283a9e79ae55ed10bdf53/tests/test_systolic_array.py#L85-L112
