### ISSUE TITLE
[Feature] Scalar Support in Function Interface

### ISSUE THREAD

**Issue by AdrianLiu00** [cornell-zhang/allo#218]
**Is your feature request related to a problem? Please describe.**
The direct operation and return for scalar variable in function arguments will cause problem since MLIR doesn't support MemRefType for Scalar.

**Describe the solution you'd like**
Maybe automatically modify the scalar argument as an array with length 1 when building IR.

**Additional context**
A simple test case provided.
```
def test_scalar():
    def case1(C: int32) -> int32:
        return C
    
    s = allo.customize(case1)
    code = s.build(target="vitis_hls")
```
And its error info:
`ValueError: Cannot cast type to MemRefType (from Type(i32))`

**Comment by chhzh123** [comment]
Fixed in #219
